### ISSUE TITLE
Model Error

### ISSUE THREAD

**Issue by Elvincth** [thekevinscott/ml-classifier-ui#6]
start();
 async function start() {
const model = await tf.loadLayersModel('model.json');
const example =  tf.browser.fromPixels(document.getElementById('test'));  // for example
const prediction = model.predict(example);
    }

errors.ts:48 Uncaught (in promise) Error: Error when checking : expected flatten_Flatten1_input to have 4 dimension(s), but got array with shape [640,960,3]
    at new e (errors.ts:48)
    at Dd (training.ts:311)
    at e.predict (training.ts:1073)
    at e.predict (models.ts:765)
    at start ((index):31)

**Comment by thekevinscott** [comment]
It looks like you may need to resize your image. Can you provide a code sandbox link?

**Comment by Elvincth** [comment]
Yes , I did follow your article for resizing the image , here is my code thanks for helping out. 
[test.zip](https://github.com/thekevinscott/ml-classifier-ui/files/3193631/test.zip)

**Comment by thekevinscott** [comment]
You are loading the wrong model. You're loading your own model and trying to use that for activations; you should be using mobilenet.

Try replacing `loadTruncatedMobileNet` with the following:

```
async function loadTruncatedMobileNet() {
    const pretrainedModelURL = 'https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json';
    const mobilenet = await tf.loadLayersModel(pretrainedModelURL);

    const layer = mobilenet.getLayer('conv_pw_13_relu');
    return tf.model({inputs: mobilenet.inputs, outputs: layer.output});

  }
  async function loadModel() {
    return await tf.loadLayersModel('ml-classifier-Super_Galaxy-Super_Snow.json');
  }

  async function start() {
      truncatedMobileNet = await loadTruncatedMobileNet();
      model = await loadModel();
...
```

You can call `model.summary()` to inspect the shape of your model. You'll see that it expects a different shape.

**Comment by Elvincth** [comment]
The model was generated by your ml classifier

**Comment by thekevinscott** [comment]
It still needs to process the images through mobilenet for the initial activation.

**Comment by Elvincth** [comment]
OK , many thanks!

**Comment by thekevinscott** [comment]
Sure! Let me know if you run into any problems.

As an FYI, you _can_ create a single model that combines the pretrained model with your own layers. I don't have any code showing how to do this, but high level you'd want to construct a sliced model from mobilenet, make sure the existing layers are frozen (aka, ensure they won't be trainable), and then concatenate your own unfrozen layers onto the model.

I prefer the approach shown here, where the pretrained model exists separately from your model, because it gives more flexibility on the UX side to process data. For instance, you can activate the images through mobilenet when the user uploads them, instead of having to do it all in one big step.

**Comment by Elvincth** [comment]
Yes understand, again big thanks for your help, I am just into tensor flow your work really helped me out, keep it up !
